### ISSUE TITLE
Error caused by Stash

### ISSUE THREAD

**Issue by CorLeonas** [tmedwards/CoCEd#25]
[CoCEd: 1.3.1.28497, CoC Data: 1.0.2_mod_1.4.16c]
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoCEd.ViewModel.GameVM.UpdateChest() in C:\Users\tmedwards\Documents\Visual Studio 2015\Projects\CoCEd\CoCEd\ViewModel\GameVM.Core.cs:line 239
   at CoCEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM, Boolean isRevampMod) in C:\Users\tmedwards\Documents\Visual Studio 2015\Projects\CoCEd\CoCEd\ViewModel\GameVM.cs:line 135
   at CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup) in C:\Users\tmedwards\Documents\Visual Studio 2015\Projects\CoCEd\CoCEd\ViewModel\VM.cs:line 125
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tmedwards** [comment]
See if the [latest release (v1.3.2)](https://github.com/tmedwards/CoCEd/releases/latest) resolves the issue.

**Comment by CorLeonas** [comment]
Trying to run the newest version of CoCEd gives me this error no matter where I place the files. I've also tried running it directly from Winrar to no avail. Reverting back to the previous version (1.3.1) still works.
![Capture](https://user-images.githubusercontent.com/51346033/59697783-4ed83600-91a3-11e9-94f2-b0dc0f651aa8.PNG)

**Comment by tmedwards** [comment]
CoCEd does not come with a Xianxia data file.  Copy your old one, or a new one, into the directory.

**Comment by CorLeonas** [comment]
The weird thing is I don't know what that file is. I've never seen it before and when I try running the previous versions, it works perfectly fine. It's only 1.3.2 that I'm having problems with. I'll try to mess around with stuff a bit more to see if I cant find out what's causing it.

**Comment by tmedwards** [comment]
The [latest release (v1.3.3)](https://github.com/tmedwards/CoCEd/releases/latest) should fix the Xianxia issue.

**Comment by CorLeonas** [comment]
Ok, after messing around with storage, I can confirm the newest versions of both CoCEd and the game work. I still get an error when trying to load some of my older save files but it can be solved by just putting something into a chest and saving. After putting anything into the basic chest and loading that file again, it doesn't crash anymore. I'll post the error just in case you want it.
[CoCEd: 1.3.3.223, CoC Data: 1.0.2_mod_1.4.16c]
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoCEd.ViewModel.GameVM.GetItemStorageObj() in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\GameVM.Core.cs:line 252
   at CoCEd.ViewModel.GameVM.UpdateChest() in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\GameVM.Core.cs:line 257
   at CoCEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM, ModType modType) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\GameVM.cs:line 144
   at CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\VM.cs:line 151
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
